name: Automatic Publish
on: 
  push: 
    branches: 
      - main
jobs:
  Release:
    runs-on: ubuntu-latest
    steps:
      - name: Unit Test
        run: |
          yarn test

      - name: Build
        run: |
          yarn build

      - name: Automated releases for npm packages
        uses: mikeal/merge-release@v4.0.7

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false




